[package]
name = "the_little_cosmonaut_wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "22.0.0"
winit = "0.30.4"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tokio = { version = "1", features = ["full"] }
tokio-macros = "2.4.0"
